### ISSUE TITLE
MT2 fingers get "stuck" causing certain gestures to stop working (e.g. notification center)

### ISSUE THREAD

**Issue by coolstar** [alexandred/VoodooI2C#139]
With some gestures, some fingers may get "stuck" which causes some gestures to stop working. This is easily verified with FingerMgmt https://github.com/jnordberg/FingerMgmt

**Comment by coolstar** [comment]
commit e3c9727efb77e6a9bfc2be09230837ef1eedd6cb helps a bit, though some fingers still get stuck

**Comment by BesnikRrustemi** [comment]
Unfortunately, the situation is the same 
I did build from source with your latest changes again.
Gestures don't work, cursor still sometimes jumps on top of the screen, and right click doesn't work even with 2 fingers tap.

**Comment by coolstar** [comment]
For new commenters, please check trackpad operation with FingerMgmt. Gestures can break for a number of reasons; we need to verify the touch data is working correctly (and if not, which part is broken): https://github.com/jnordberg/FingerMgmt/releases

**Comment by gujiangjiang** [comment]
With the newest VoodooI2C source code and tested blow:


when my 5 fingers put to the touchpad it can detect very well and smoothly.
<img width="526" alt="qq20181220-003823 2x" src="https://user-images.githubusercontent.com/13273955/50234027-b4638980-03ef-11e9-9895-d521f39a93a3.png">

But when i move my fingers from touchpad it show 4 circles in [FingerMgmt] and it will distirub the notification center gesture.
<img width="526" alt="qq20181220-003842 2x" src="https://user-images.githubusercontent.com/13273955/50234161-ff7d9c80-03ef-11e9-81e4-80f8c23749ca.png">

**Comment by coolstar** [comment]
Fixed in bcf0694a64a260ba3b219e7ce9679cfbd69a2882

**Comment by BesnikRrustemi** [comment]
> Fixed in [bcf0694](https://github.com/alexandred/VoodooI2C/commit/bcf0694a64a260ba3b219e7ce9679cfbd69a2882)

i Build kext with this commit and the cleanup that you added, now FingerMgmt only detects one finger, i try two,three,four and it only shows 1 finger.

**Comment by BesnikRrustemi** [comment]
@andrewwyatt are you referring to today changes ?
Haven’t tested the two commits that @coolstar pushed today as im at work right now.
Will build as soon as i get home and test it, then report back with results.
I hope it’s fixed so hopefully we can track and fix right click problems.
That would be a life changer.

**Comment by BesnikRrustemi** [comment]
Thanks @gujiangjiang , i have it ready now so when i go home i only install and test it.

Mine is ELAN0618 precision touchpad. My results with this are mixed, for example.

1.VoodooI2C.kext + VoodooI2CELAN.kext works all fine with the scaling workaround, only issue is right click not working, workaround is to use two finger tap to right click.

2. VoodooI2C.kext + VoodooI2CHID.kext i have left & right click working incredibly well (better than windows with the original driver from lenovo) but sysprefs>TrackPad says not trackpad found. With this combo i have no gestures and no scrolling, only cursor, left and right click.

If i can modify the kext to detect trackpad with voodooi2chid.kext and maybe then gestures would work as well, that would be phenomenal as i will have working right click too.

**Comment by andrewwyatt** [comment]
@BesnikRrustemi yes, I was testing today's commits.  Two finger right click is still broken, as is one finger click (or tap), second finger drag.  These commits don't appear to address those though.

[VoodooI2C.zip](https://github.com/alexandred/VoodooI2C/files/2698957/VoodooI2C.zip)

**Comment by alexandred** [comment]
@andrewwyatt are you sure you're running the latest commit? I have all those issues fixed with the latest commit on VoodooI2CHID.kext

**Comment by alexandred** [comment]
@BesnikRrustemi please provide individual troubleshooting archives for both VoodooI2CHID and VoodooI2CELAN.

**Comment by andrewwyatt** [comment]
@alexandred - I do have the latest commits.  I didn't realize you had fixed those things, so I was still using tap to click.  Just turned it off and your changes do indeed fix two finger click and one finger click + drag.

**Comment by BesnikRrustemi** [comment]
@alexandred , i will upload files for you after 2.5 - 3 hours as soon as i get back home.

It would be amazing if we can make my touchpad work with gestures on VoodooI2CHID.kext

**Comment by BesnikRrustemi** [comment]
OMG thank you guys sooo much.

@gujiangjiang thanks for the kext mate.
@coolstar i just tested and now everything works perfect, even right click is working after i changed Sysprefs > Trackpad > Point & Click tab > Secondary click
i was using: click or tap with two fingers, now i set it to click on the right corner and it does work perfect
Even dragging works perfect, gestures etc.

Amazing work.

**Comment by BesnikRrustemi** [comment]
@alexandred i think you guys should push an update now, right click working for me now, just have to change it from two fingers tap or click to click on right corner, the scaling issue fixed the right click as well for me.

I think the others should test that to, we just have to point that they need to do the change on Sysprefs:
![right click](https://user-images.githubusercontent.com/30008333/50299123-13251380-0481-11e9-8352-f866f957c0bb.png)

**Comment by Kmbeatz** [comment]
Yes right Click is Finaly Working. Thank you so much. Awesome work from all.

**Comment by BesnikRrustemi** [comment]
Can someone of you test CPU Usage on activity monitor, see **hidd** task cpu usage goes higher when touching the touchpad (moving, gesture, clicking or whatever).
For me it goes to 25% cpu usage when i use touchpad, i would like to know if it is a general problem for now or i have wrong pin number.

**Comment by andrewwyatt** [comment]
The hidd process is never exceeding 7% CPU for me.

**Comment by BesnikRrustemi** [comment]
Fixed, 5.1% is the maximum i got, wasn’t using the very latest build from source.
100% perfect working for me now

**Comment by best-sda** [comment]
elan 1200 absolutely not working in last commit voodooi2c+ i2cHID

**Comment by x-tropic** [comment]
on the last build voodoosynaptics earned dragging files with one finger...  when i swipe, the cursor starts selecting objects (without press and hold left or right button). I have 2 button on my trackpad and right button have same function as left (2 left button).
Device ID: SYNA2B33.

**Comment by Mateo1234454545** [comment]
Just an update.
Newest commits work on Mojave but not on HS. On HS tracpad is not recognised at all.

**Comment by Mateo1234454545** [comment]
> @BesnikRrustemi yes, I was testing today's commits. Two finger right click is still broken, as is one finger click (or tap), second finger drag. These commits don't appear to address those though.
> 
> [VoodooI2C.zip](https://github.com/alexandred/VoodooI2C/files/2698957/VoodooI2C.zip)

Is it possible to upload latest voodooi2c commits.
I tried to build it but gave me error.

**Comment by alexandred** [comment]
Closed as this issue has been fixed with the latest upstream.
